### ISSUE TITLE
why can yellow bar be showed on the bottom of scrollview?

### ISSUE THREAD

**Issue by mmm2006** [woelmer/UIScrollViewWithAutoLayout#5]
I just read your blog and try your code. It is great. I add two lanes which have many lines text data. it work great if I set line attribute to 0 for label.  It should be this, right?

But  I don't understand why can yellow bar be showed on the bottom of scrollview? Please help me about this. 

thanks

**Comment by woelmer** [comment]
In the demo the scroll view has a yellow background to demonstrate where it is. In portrait view my content does not go all the way to the bottom of the phone, so you see the bottom portion of the scroll view. In landscape you do not see yellow. This is not a bug.
